name: Validate JSON

on:
  pull_request:
    types: [closed]
    branches:
      - master
jobs:
  verify-json-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Validate JSON
        uses: OrRosenblatt/validate-json-action@0.1.0
          INPUT_JSONS: /src/assets/i18n/en.json
