name: Validate JSON

on:
  push:
    branches:
      - redesign
jobs:
  github_action_json_lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Validate JSON
      uses: ilmartyrk/github-action-json-lint@33b75f20d2bdc10e36082322be93cc775978ea9a
      with:
        path-to-file: 'src/assets/i18n/en.json'
